### ISSUE TITLE
Not respecting uniqueness

### ISSUE THREAD

**Issue by paulshannon** [Brobin/django-seed#13]
https://github.com/Brobin/django-seed/blob/master/django_seed/seeder.py#L30-L36

This pulls a random value from inserted values; it needs to be one to one.

**Comment by Brobin** [comment]
Good catch. This shouldn't be too difficult to fix. We will need to maintain another list (like inserted_entities), perhaps a hash to keep track of entities that have been used for OneToOne relationships.

**Comment by paulshannon** [comment]
This is also a problem on other fields with `unique=True`. I think a more general solution is required.

**Comment by Dzordzu** [comment]
Any updates on this?

**Comment by AngelOnFira** [comment]
Ya, there is a PR right now that is working on this, but I need to clean it up. Then I need to write some tests that provides a lot of guarentees around this, since I think there is a lot of ground to cover.

**Comment by smoeinbbp** [comment]
Any updates on this?

**Comment by AngelOnFira** [comment]
Resolved as part of #97.

**Comment by aryan9600** [comment]
I still encounter an error while populating two tables with a one to one mapping.

```python
seeder = Seed.seeder()
seeder.add_entity(FileSet, 5_000)
seeder.add_entity(File, 5_000)
seeder.execute()
```

```
django.db.utils.IntegrityError: duplicate key value violates unique constraint "classif_ai_file_file_set_id_key"
DETAIL:  Key (file_set_id)=(254) already exists.
```
